name: demo test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
      with:
            node-version:19.9.0

      - name: Run a one-line script
        run: echo Hello from Octo Organization
